<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!-- Paket NuGet -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.5" />

		<!-- Referensi ke project lain -->
		<ProjectReference Include="..\MyBlazorHybridApp.Web.Client\MyBlazorHybridApp.Web.Client.csproj" />
		<ProjectReference Include="..\MyBlazorHybridApp.Shared\MyBlazorHybridApp.Shared.csproj" />
	</ItemGroup>

</Project>
